'use client';

import React, { useState } from 'react';
import * as XLSX from 'xlsx';

interface POAMItem {
  poamId: string;
  controls: string;
  weaknessName: string;
  weaknessDesc: string;
  detectorSource: string;
  assetId: string;
  poc: string;
  detectionDate: string;
  riskRating: 'Critical' | 'High' | 'Moderate' | 'Low';
  remediationPlan: string;
  scheduledDate: string;
}

export default function FedRAMPPOAMBuilder() {
  const [items, setItems] = useState<POAMItem[]>([]);
  const [formData, setFormData] = useState({
    poamId: 'VS-001',
    controls: 'RA-5, SC-13',
    weaknessName: '',
    weaknessDesc: '',
    detectorSource: 'Nessus / STIG',
    assetId: '',
    poc: 'Security Ops',
    detectionDate: new Date().toISOString().split('T')[0],
    riskRating: 'High' as const,
    remediationPlan: '',
  });

  const calculateScheduledDate = (detectionDate: string, risk: string): string => {
    const date = new Date(detectionDate);
    const days = risk === 'Critical' || risk === 'High' ? 30 : risk === 'Moderate' ? 90 : 180;
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
  };

  const addItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.weaknessName || !formData.weaknessDesc) return;

    const scheduledDate = calculateScheduledDate(formData.detectionDate, formData.riskRating);

    const newItem: POAMItem = {
      ...formData,
      scheduledDate,
    };

    setItems([...items, newItem]);
    
    // Reset form with incremented ID
    setFormData({
      ...formData,
      poamId: `VS-${String(items.length + 2).padStart(3, '0')}`,
      weaknessName: '',
      weaknessDesc: '',
      assetId: '',
      remediationPlan: '',
    });
  };

  const removeItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const exportToExcel = () => {
    if (items.length === 0) {
      alert('Add at least one item before exporting');
      return;
    }

    const wb = XLSX.utils.book_new();
    const wsData = [
      ['FedRAMP POA&M - Generated by Genesis Conductor Toolkit'],
      ['CSP: Kovach Enterprises', 'CSO: Genesis Conductor', `Date: ${new Date().toISOString().split('T')[0]}`],
      [],
      ['POAM ID', 'Controls', 'Weakness Name', 'Description', 'Risk', 'Scheduled Date', 'Remediation Plan'],
      ...items.map(item => [
        item.poamId,
        item.controls,
        item.weaknessName,
        item.weaknessDesc,
        item.riskRating,
        item.scheduledDate,
        item.remediationPlan
      ])
    ];

    const ws = XLSX.utils.aoa_to_sheet(wsData);
    XLSX.utils.book_append_sheet(wb, ws, 'POA&M Items');
    XLSX.writeFile(wb, `FedRAMP-POAM-${new Date().toISOString().slice(0,10)}.xlsx`);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <nav className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between h-16">
          <div className="flex items-center gap-x-3">
            <div className="w-8 h-8 bg-[#0A2540] rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-sm">FR</span>
            </div>
            <span className="font-semibold text-xl tracking-tight">FedRAMP POA&M Builder</span>
            <span className="text-xs px-2 py-0.5 bg-emerald-100 text-emerald-700 rounded-full">Next.js</span>
          </div>
          <div className="flex items-center gap-x-3">
            <button 
              onClick={exportToExcel}
              className="px-5 py-2 bg-emerald-600 text-white rounded-2xl text-sm font-medium flex items-center gap-x-2 hover:bg-emerald-700"
            >
              <span>Export to Excel</span>
            </button>
            <a 
              href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Figor-holt%2Ffedramp-poa-m-toolkit&root-directory=web" 
              className="px-4 py-2 text-sm border rounded-2xl hover:bg-white"
            >
              Deploy
            </a>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
          {/* Form */}
          <div className="lg:col-span-2 bg-white rounded-3xl border p-7">
            <h2 className="font-semibold text-lg mb-5">Add POA&M Item</h2>
            
            <form onSubmit={addItem} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs font-medium text-slate-600">POAM ID</label>
                  <input 
                    type="text" 
                    value={formData.poamId}
                    onChange={(e) => setFormData({...formData, poamId: e.target.value})}
                    className="w-full mt-1 px-4 py-2 border rounded-2xl text-sm" 
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-600">Risk Rating</label>
                  <select 
                    value={formData.riskRating}
                    onChange={(e) => setFormData({...formData, riskRating: e.target.value as any})}
                    className="w-full mt-1 px-4 py-2 border rounded-2xl text-sm bg-white"
                  >
                    <option value="Critical">Critical</option>
                    <option value="High">High</option>
                    <option value="Moderate">Moderate</option>
                    <option value="Low">Low</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="text-xs font-medium text-slate-600">Weakness Name</label>
                <input 
                  type="text" 
                  value={formData.weaknessName}
                  onChange={(e) => setFormData({...formData, weaknessName: e.target.value})}
                  className="w-full mt-1 px-4 py-2 border rounded-2xl text-sm" 
                  required 
                />
              </div>

              <div>
                <label className="text-xs font-medium text-slate-600">Description</label>
                <textarea 
                  value={formData.weaknessDesc}
                  onChange={(e) => setFormData({...formData, weaknessDesc: e.target.value})}
                  className="w-full mt-1 px-4 py-2 border rounded-3xl text-sm h-20" 
                  required 
                />
              </div>

              <button 
                type="submit"
                className="w-full py-3 bg-[#0A2540] text-white rounded-3xl font-semibold text-sm tracking-wider mt-2"
              >
                ADD TO POA&M
              </button>
            </form>
          </div>

          {/* Table */}
          <div className="lg:col-span-3 bg-white rounded-3xl border overflow-hidden">
            <div className="px-7 py-5 border-b flex items-center justify-between">
              <div className="font-semibold">Current Items ({items.length})</div>
              <button 
                onClick={() => setItems([])}
                className="text-xs text-red-500 hover:text-red-600"
              >Clear All</button>
            </div>
            
            <div className="overflow-auto max-h-[500px]">
              <table className="w-full text-sm">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="px-6 py-3 text-left font-medium text-xs">ID</th>
                    <th className="px-6 py-3 text-left font-medium text-xs">Weakness</th>
                    <th className="px-6 py-3 text-left font-medium text-xs">Risk</th>
                    <th className="px-6 py-3 text-left font-medium text-xs">Scheduled</th>
                    <th className="w-10"></th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {items.length === 0 && (
                    <tr>
                      <td colSpan={5} className="px-6 py-12 text-center text-slate-400 text-xs">
                        No items yet. Add your first finding using the form.
                      </td>
                    </tr>
                  )}
                  {items.map((item, index) => (
                    <tr key={index} className="hover:bg-slate-50">
                      <td className="px-6 py-4 font-mono text-xs text-blue-700">{item.poamId}</td>
                      <td className="px-6 py-4">
                        <div className="font-medium text-sm line-clamp-1">{item.weaknessName}</div>
                        <div className="text-xs text-slate-500 line-clamp-1">{item.controls}</div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`text-xs px-2.5 py-0.5 rounded-full font-medium ${
                          item.riskRating === 'Critical' || item.riskRating === 'High' ? 'bg-red-100 text-red-700' : 
                          item.riskRating === 'Moderate' ? 'bg-orange-100 text-orange-700' : 'bg-emerald-100 text-emerald-700'
                        }`}>
                          {item.riskRating}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-mono text-xs text-slate-600">{item.scheduledDate}</td>
                      <td className="px-4 py-4">
                        <button onClick={() => removeItem(index)} className="text-red-400 hover:text-red-600">
                          <i className="fa-solid fa-times"></i>
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}